import "./globals.css";

import localFont from "next/font/local";

const pixelFont = localFont({
  src: [
    {
      path: "../../public/fonts/PixelifySans-Regular.ttf",
      weight: "400",
    },
    {
      path: "../../public/fonts/PixelifySans-Medium.ttf",
      weight: "500",
    },
    {
      path: "../../public/fonts/PixelifySans-SemiBold.ttf",
      weight: "600",
    },
    {
      path: "../../public/fonts/PixelifySans-Bold.ttf",
      weight: "700",
    },
  ],
  variable: "--font-pixel",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${pixelFont.variable} font-pixel`}>
        {children}
      </body>
    </html>
  );
}
